version: '3.7'

services:
  email-engine-core:
    build:
      context: .
      dockerfile: Dockerfile
    image: email-engine-core
    ports:
      - 3000:3000
    env_file: .env.docker
    volumes:
      - ./:/app
    depends_on:
      - postgres-email-engine-core
      - elasticsearch
    environment:
      - npm_config_cache=/home/node/.npm

  postgres-email-engine-core:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:8.16.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    memswap_limit: 2g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  postgres-data:
  elasticsearch-data:
